### ISSUE TITLE
Issue with reusing common rules and params across the board

### ISSUE THREAD

**Issue by jseifeddine** [sol1-ansible/sol1-shorewall#4]
Hi Guys 

We seem to have common rules and params that could be reused across the entire org...

A bit of a pain to have to go and rember to update each host / group rule each time there are changes to your "safe ips" 

Anyway so because there doesn't seem to be a nice way to 'merge' without filter plugins, i though i would share how I have tackled this use case:

global shorewall group_var:
```yaml
shorewall_run: true

common_shorewall_params:
  - { name: "management", value: "100.250.100.0/24,200.150.200.0/24" }
  - { name: "safeips", value: "101.102.103.104,105.106.107.222" }

common_shorewall_rules:
  - section: NEW
    rules:
    - { comment: "Drop everything", action: "Invalid(DROP)", source: net, dest: "$FW", proto: "tcp,udp" }
    - { comment: "Allow Management and Safe IPs", action: ACCEPT, source: "net:$management,$safeips", dest: "$FW" }
```

Then the only changes i've made to the role is in `tasks/shorewall.yml` just before `Generate Shorewall essential configuration files`, replacing the `shorewall_rules` var when suitable.
```yaml
- name: prepend common_shorewall_rules to shorewall_rules
  set_fact: 
    shorewall_rules: "{{ merged_sorted_rules | from_yaml }}"
  vars:
    _rules_combined: "{{ (common_shorewall_rules | default({}), shorewall_rules | default({}) ) | community.general.lists_mergeby('section', recursive=true, list_merge='append') }}"
    merged_sorted_rules: |
      {%- set section_order = ['ALL', 'ESTABLISHED', 'RELATED', 'INVALID', 'UNTRACKED', 'NEW'] %}
      {%- set ordered_rules = [] %}
      {%- for section in section_order %}
        {%- for rule in _rules_combined %}
          {%- if rule.section == section %}
            {%- set _ = ordered_rules.append(rule) %}
          {%- endif %}
        {%- endfor %}
      {%- endfor %}
      {%- set unordered_rules = _rules_combined | rejectattr('section', 'in', section_order) | list %}
      {%- set final_rules = ordered_rules + unordered_rules %}
      {{ final_rules | to_yaml }}
  when: common_shorewall_rules is defined
```

and then right before `Generate Shorewall params configuration file`, replacing the `shorewall_params` var. 
```yaml
- name: prepend common_shorewall_params to shorewall_params
  set_fact:
    shorewall_params: "{{ merged_params_yaml | from_yaml }}"
  vars:
    _params_combined: "{{ common_shorewall_params | default([]) + shorewall_params | default([])  }}"
    merged_params_yaml: |
      {%- set temp = {} %}
      {%- for param in _params_combined %}
        {%- if param['name'] in temp %}
          {%- set _ = temp.update({ param['name']: temp[param['name']] ~ ',' ~ param['value'] }) %}
        {%- else %}
          {%- set _ = temp.update({ param['name']: param['value'] }) %}
        {%- endif %}
      {%- endfor %}
      {%- set result = [] %}
      {%- for name, value in temp.items() %}
        {%- set _ = result.append({'name': name, 'value': value}) %}
      {%- endfor %}
      {{ result }}
  when: common_shorewall_params is defined
```

None of the filter plugins (i tried them all) would dedupe and merge the list of dicts in params. 

The rules were more straight forward, because I didn't set out to merge them. 

I was hell bent on making it work - took me ages...

Now your gonna tell me theres a much better way 🤣 

EDIT: cleaned a bit of the logic 

Peace !
